name: CI

on:
  push:
    branches: [main, develop, master]
  pull_request:
    branches: [main, develop, master]
  schedule:
    - cron: '0 18 * * 1'

jobs:
  lint:
    uses: jyw-sata/devops/.github/workflows/lint.yml@main

  codeql:
    uses: jyw-sata/devops/.github/workflows/codeql.yml@main
    with:
      language: javascript
